using Units.Visual;
using UnityEngine;
using Utilities;

namespace Pool.LifeBar
{
    public class BarLifePool : SingletonAutoGenerated<BarLifePool>
    {
        [SerializeField] private BarLife _barLife;
        [SerializeField] private int amount;
        
        private BarLifeFactory barLifeFactory;

        private void Awake() => barLifeFactory = new BarLifeFactory(_barLife, amount);

        public void ReturnObject(BarLife item)
        {
            barLifeFactory.ReturnObject(item);
        }

        public BarLife CreateObject()
        {
            return barLifeFactory.CreateObject();
        }
    }
}
