using UnityEngine;
using Utilities;

namespace Pool.BarLife
{
    public class BarLifePool : SingletonAutoGenerated<BarLifePool>
    {
        [SerializeField] private PoolCanvasConfigurationSO _canvasConfigurationSO;

        private CanvasFactory _canvasFactory;

        private void Awake() => _canvasFactory = new CanvasFactory(_canvasConfigurationSO);

        public void ReturnObject(string id, Units.Visual.BarLife item)
        {
            _canvasFactory.ReturnObject(id, item);
        }

        public Units.Visual.BarLife CreateObject(string id)
        {
            return _canvasFactory.CreateObject(id);
        }
    }
}
