using UnityEngine;

namespace Utilities
{
    public abstract class SingletonAutoGenerated<T> : MonoBehaviour where T : Component
    {
        [SerializeField] private bool _dontDestroyOnLoad;
        
        protected static T instance;

        public static bool HasInstance => Instance != null;
        public static T TryGetInstance() => HasInstance ? Instance : null;

        public static T Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = FindObjectOfType<T>();
                    if (instance == null)
                    {
                        var go = new GameObject(typeof(T).Name + "Auto - Generated");
                        instance = go.AddComponent<T>();
                    }
                }

                return instance;
            }
        }

        private void Awake() => InitializeSingleton();

        protected virtual void InitializeSingleton()
        {
            if (!Application.isPlaying) return;

            instance = this as T;
            
            if (!_dontDestroyOnLoad) return;
            
            DontDestroyOnLoad(gameObject);
        }
    }
}
