using System.Collections.Generic;
using System.Linq;
using Structures;
using Units;
using UnityEngine;
using Utilities;

namespace Manager
{
    public class GameManager : SingletonAutoGenerated<GameManager>
    {
        [SerializeField] private List<Center> _centers = new();
        
        [SerializeField] private LayerMask _unitLayer;
        [SerializeField] private LayerMask _unitStructureLayer;
        [SerializeField] private LayerMask _resourceLayer;
        [SerializeField] private LayerMask _treesLayer;
        [SerializeField] private LayerMask _groundLayer;
        
        public LayerMask GetUnitLayer() => _unitLayer;
        public LayerMask GetUnitStructureLayer() => _unitStructureLayer;
        public LayerMask GetResourceLayer() => _resourceLayer;
        public LayerMask GetTreesLayer() => _treesLayer;
        public LayerMask GetGroundLayer() => _groundLayer;

        public void AddCenter(Center center)
        {
            _centers.Add(center);
        }

        public void RemoveCenter(Center center)
        {
            _centers.Remove(center);
        }

        public Center NearCenter(Unit unit)
        {
            return _centers.OrderBy(center => (center.transform.position - unit.transform.position).sqrMagnitude).FirstOrDefault();
        }
    }
}